---
title: Tet.ai
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: 
description: Tet.ai create chatbots to train people-smart staff.
baseurl: 
url: https://www.tet.ai
social:
- title: twitter
  url: https://twitter.com/tet_ai
- title: facebook
  url: https://www.facebook.com/wearetet
- title: google-plus
  url: https://plus.google.com/+user
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude:
- less
- node_modules
- Gruntfile.js
- package.json
- README.md
plugins:
- jekyll-paginate
- jekyll-feed
theme: jekyll-theme-minimal
