---
title: Tet.ai
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: 
description: Tet.ai
baseurl: ''
url: https://tet-ai.github.io/
social:
- title: twitter
  url: https://twitter.com/user
- title: facebook
  url: https://facebook.com/user
- title: google-plus
  url: https://plus.google.com/+user
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude:
- less
- node_modules
- Gruntfile.js
- package.json
- README.md
plugins:
- jekyll-paginate
- jekyll-feed
theme: jekyll-theme-minimal
